version: "3.8"
services:
  vms-client:
    container_name: web-vms
    image: vmsacr.azurecr.io/web-vms:latest
    restart: always
    ports:
      - "3000:80" # map 80 in container => 3000 in local
    environment:
#      - REALM_NAME=https://idm-vms.azurewebsites.net/
#      - AUTH_SERVER_URL=vms
#      - SSL_REQUIRED=external
#      - VERIFY_TOKEN_AUDIENCE=true
#      - USE_RESOURCE_ROLE_MAPPINGS=true
#      - CLIENT_ID=vms-app
#      - CLIENT_SECRET=7r5uiBkk4lDoXKzwt20UYWACNRxwfeZD
      - API_SERVER_URL=https://api-vms.azurewebsites.net/api/v1
      - STORAGE_URL=https://vmscloudstorage.blob.core.windows.net/vms-file-storage/
      - BASE_PATH=
