export const PATH_ROLE_MAP = {
  'PATH_DASHBOARD': ['path:dashboard'],
  'PATH_CONFIGURATION': ['path:configuration'],
  'PATH_CUSTOMER': ['path:customer'],
  'PATH_DEPARTMENT': ['path:department'],
  'PATH_DEVICE': ['path:device'],
  'PATH_HISTORY': ['path:history'],
  'PATH_MEETING_CALENDAR': ['path:meeting_calendar'],
  'PATH_MEETING_STATISTIC': ['path:meeting_statistic'],
  'PATH_MEETING_ROOM': ['path:meeting_room'],
  'PATH_ORGANIZATION': ['path:organization'],
  'PATH_MY_ORGANIZATION': ['path:my_organization'],
  'PATH_MY_SITE': ['path:my_site'],
  'PATH_AUDIT_LOG': ['path:audit_log'],
  'PATH_PERMISSION': ['path:permission'],
  'PATH_PROFILE': ['path:profile'],
  'PATH_ROOM': ['path:room'],
  'PATH_SITE': ['path:site'],
  'PATH_TEMPLATE': ['path:template'],
  'PATH_TICKET_RESULT': ['path:ticket_result'],
  'PATH_CHECK_IN_MANAGER': ['path:check_in_manager'],
  'PATH_QR_CODE_MANAGER': ['path:qr_code_manager'],
  'PATH_USER': ['path:user'],
  'PATH_ROLE': ['path:role']
}

export const SCOPE_ROLE_MAP = {
  'SCOPE_ORGANIZATION': ['scope:organization'],
  'SCOPE_SITE': ['scope:site']
}

export const PERMISSION_ROLE_MAP = {
  'R_DEVICE_UPDATE': ['r:device:update'],
  'R_PERMISSION_FIND': ['r:permission:find'],
  'R_TEMPLATE_FILTER': ['r:template:filter'],
  'R_DEVICE_DELETE': ['r:device:delete'],
  'R_SETTING-SITE_DELETE': ['r:setting-site:delete'],
  'R_TICKET_CANCEL': ['r:ticket:cancel'],
  'R_USER_DOWNLOAD-TEMPLATE': ['r:user:download-template'],
  'R_DEPARTMENT_DELETE': ['r:department:delete'],
  'R_SITE_CREATE': ['r:site:create'],
  'R_ROLE_UPDATE': ['r:role:update'],
  'R_TEMPLATE_DETAIL': ['r:template:detail'],
  'R_ROLE_DELETE': ['r:role:delete'],
  'R_USER_CREATE': ['r:user:create'],
  'R_TEMPLATE_CREATE': ['r:template:create'],
  'R_CUSTOMER_FILTER': ['r:customer:filter'],
  'R_TICKET_FILTER': ['r:ticket:filter'],
  'R_TICKET_UPDATE_STATUS_CUSTOMER': ['r:ticket:updateStatusCustomer'],
  'R_CUSTOMER_CHECK': ['r:customer:check'],
  'R_ACCESS-HISTORY_FILTER': ['r:access-history:filter'],
  'R_ROLE_FILTER': ['r:role:filter'],
  'R_SETTING-SITE_DETAIL': ['r:setting-site:detail'],
  'R_SITE_FILTER': ['r:site:filter'],
  'R_TEMPLATE_UPDATE': ['r:template:update'],
  'R_ROOM_DELETE': ['r:room:delete'],
  'R_USER_IMPORT': ['r:user:import'],
  'R_DEPARTMENT_UPDATE': ['r:department:update'],
  'R_AUDIT-LOG_EXPORT': ['r:audit-log:export'],
  'R_CUSTOMER_DELETE': ['r:customer:delete'],
  'R_DEPARTMENT_DETAIL': ['r:department:detail'],
  'R_TICKET_CREATE': ['r:ticket:create'],
  'R_DEVICE_DETAIL': ['r:device:detail'],
  'R_SITE_DELETE': ['r:site:delete'],
  'R_DASHBOARD_VIEW': ['r:dashboard:view'],
  'R_ROLE_PREMISSION_UPDATE': ['r:role:premission:update'],
  'R_USER_FILTER': ['r:user:filter'],
  'R_ROLE_CREATE': ['r:role:create'],
  'R_ACCESS-HISTORY_EXPORT': ['r:access-history:export'],
  'R_AUDIT-LOG_FILTER': ['r:audit-log:filter'],
  'R_TICKET_ROOM': ['r:ticket:room'],
  'R_TICKET_DELETE': ['r:ticket:delete'],
  'R_TICKET_FIND_QR_CODE': ['r:ticket:findQRCode'],
  'R_SETTING-SITE_FILTER': ['r:setting-site:filter'],
  'R_SITE_DETAIL': ['r:site:detail'],
  'R_DEVICE_CREATE': ['r:device:create'],
  'R_DEPARTMENT_CREATE': ['r:department:create'],
  'R_TICKET_VIEW_CARD_CHECKIN_HISTORY': ['r:ticket:viewCardCheckInHistory'],
  'R_USER_EXPORT': ['r:user:export'],
  'R_ROOM_FILTER': ['r:room:filter'],
  'R_AUDIT-LOG_DETAIL': ['r:audit-log:detail'],
  'R_ROOM_DETAIL': ['r:room:detail'],
  'R_TICKET_UPDATE': ['r:ticket:update'],
  'R_ACCESS-HISTORY_DETAIL': ['r:access-history:detail'],
  'R_ROOM_CREATE': ['r:room:create'],
  'R_USER_UPDATE': ['r:user:update'],
  'R_TICKET_DETAIL': ['r:ticket:detail'],
  'R_ROOM_UPDATE': ['r:room:update'],
  'R_DEVICE_FIND': ['r:device:find'],
  'R_CUSTOMER_DETAIL': ['r:customer:detail'],
  'R_SITE_UPDATE': ['r:site:update'],
  'R_ROLE_DETAIL': ['r:role:detail'],
  'R_TEMPLATE_DELETE': ['r:template:delete'],
  'R_TICKET_ADD-CARD': ['r:ticket:add-card'],
  'R_SETTING-SITE_CREATE': ['r:setting-site:create'],
  'R_SETTING-SITE_SET-DEFAULT': ['r:setting-site:set-default'],
  'R_DEPARTMENT_FILTER': ['r:department:filter']
}

export const REALM_ROLE_MAP = {
  'REALM_ADMIN': ['REALM_ADMIN']
}
